import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import "dayjs/locale/ko";
import dayjs from "dayjs";
import MonitoringInitializer from "@/components/MonitoringInitializer";
import {
  GoogleSearchEngineMetaTag,
  NaverSearchEngineMetaTag,
} from "@/components/SearchEngineMetaTags";

const inter = Inter({ subsets: ["latin"] });

dayjs.locale("ko");

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head></head>
      <GoogleSearchEngineMetaTag />
      <NaverSearchEngineMetaTag />
      <body className={inter.className}>
        <MonitoringInitializer />
        {children}
      </body>
    </html>
  );
}
